spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://localhost:3306/tw_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
